using TaskMaster.Library.Producer.Attributes;

namespace TaskMaster.Demo.Web.Domain;

/// <summary>
/// Payload contract for the demo report job.
///
/// This is intentionally duplicated in TaskMaster.Demo.Consumer rather than shared: the
/// two apps are separate processes, and a real external consumer would define its own
/// copy of the wire contract. Keep <c>SubmissionId</c>, <c>Title</c> and
/// <c>RecordCount</c> in step with the consumer's copy and with the JSON Schema
/// registered in TaskMaster.
/// </summary>
[JobType(ReportJobPayload.JobTypeName, ReportJobPayload.JobTypeVersion)]
public sealed class ReportJobPayload
{
    public const string JobTypeName = "demo-report";
    public const long JobTypeVersion = 1;

    /// <summary>Correlation id generated by the demo web app. TaskMaster does not expose job ids to producers.</summary>
    public Guid SubmissionId { get; set; }

    public string Title { get; set; } = string.Empty;

    public int RecordCount { get; set; }

    /// <summary>
    /// JSON schema matching this payload. Register it in TaskMaster as a job type
    /// (POST api/job-types) so the Producer SDK can validate payloads before creating jobs.
    /// Property casing matches Newtonsoft.Json serialization (PascalCase).
    /// </summary>
    public const string SchemaJson = """
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "SubmissionId": { "type": "string", "minLength": 1 },
        "Title": { "type": "string" },
        "RecordCount": { "type": "integer", "minimum": 1 }
      },
      "required": ["SubmissionId", "Title", "RecordCount"]
    }
    """;
}
