// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskMaster.API.Data.PostgreSql;

#nullable disable

namespace TaskMaster.API.Migrations.Npgsql
{
    [DbContext(typeof(NpgsqlDbContext))]
    [Migration("20260928120346_InitialCreate_PostgreSql")]
    partial class InitialCreate_PostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskMaster.API.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedWorkerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobPublicId")
                        .HasColumnType("uuid");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedWorkerId");

                    b.HasIndex("JobPublicId")
                        .IsUnique();

                    b.HasIndex("JobTypeId", "Status")
                        .HasDatabaseName("IX_Jobs_JobTypeId_Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.JobType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.SystemActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDateTime");

                    b.ToTable("SystemActivities");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHeartBeatTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WorkerExpiresAtTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkerPublicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkerName")
                        .IsUnique();

                    b.HasIndex("WorkerPublicId")
                        .IsUnique();

                    b.HasIndex("Status", "WorkerExpiresAtTimestamp")
                        .HasDatabaseName("IX_Workers_Status_WorkerExpiresAtTimestamp");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.WorkerCapability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifyDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WorkerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("WorkerId", "JobTypeId")
                        .IsUnique();

                    b.ToTable("WorkerCapabilities");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.Job", b =>
                {
                    b.HasOne("TaskMaster.API.Entities.Worker", "AssignedWorker")
                        .WithMany()
                        .HasForeignKey("AssignedWorkerId");

                    b.HasOne("TaskMaster.API.Entities.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedWorker");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.WorkerCapability", b =>
                {
                    b.HasOne("TaskMaster.API.Entities.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskMaster.API.Entities.Worker", null)
                        .WithMany("WorkerCapabilities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("TaskMaster.API.Entities.Worker", b =>
                {
                    b.Navigation("WorkerCapabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
