using TaskMaster.Demo.Consumer.Domain;
using TaskMaster.Library.Consumer.Attributes;

namespace TaskMaster.Demo.Consumer.Domain;

/// <summary>
/// Payload contract for the demo report job. Must stay in sync with the schema
/// registered in TaskMaster and with the copy used by TaskMaster.Demo.Web.
/// </summary>
[JobType(ReportJobPayload.JobTypeName, ReportJobPayload.JobTypeVersion)]
public sealed class ReportJobPayload
{
    public const string JobTypeName = "demo-report";
    public const long JobTypeVersion = 1;

    /// <summary>Correlation id generated by the demo web app.</summary>
    public Guid SubmissionId { get; set; }

    public string Title { get; set; } = string.Empty;

    public int RecordCount { get; set; }
}
